<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>lab8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="lab8_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab8_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="lab8_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="lab8_files/libs/quarto-html/popper.min.js"></script>
<script src="lab8_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab8_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab8_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab8_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab8_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab8_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab8_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="sec-lab8" class="level1">
<h1>Logistic Regression</h1>
<p>Data: HotelGLP_Logistic.sav (available on Moodle)</p>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>The aim of this lab is to help you use SPSS to conduct logistic regression analysis, which is useful when the outcome variable has only two possible values. At the end of this lab, we hope that you will be able to</p>
<ul>
<li>Understand when logistic regression should be used instead of linear regression</li>
<li>Conduct a binary logistic regression in SPSS</li>
<li>Interpret logistic regression outputs</li>
<li>Interpret odds ratios</li>
<li>Evaluate model fit</li>
<li>Assess the predictive usefulness of a logistic regression model</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Many marketing decisions involve predicting whether something will happen or not. A customer either buys or does not buy. A customer either joins a loyalty programme or declines. Logistic regression is one of the most widely used analytical tools for answering such questions.</p>
</div>
</div>
</section>
<section id="why-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="why-logistic-regression">Why Logistic Regression?</h2>
<p>Suppose a hotel recently launched a Green Loyalty Programme (GLP). The hotel manager wants to understand which consumers are likely to join the programme. Unlike the previous workshop, the dependent variable is no longer measured on a scale from 1 to 7. Instead:</p>
<ul>
<li>Join GLP = 1</li>
<li>Do Not Join GLP = 0</li>
</ul>
<p>Because the dependent variable is binary, ordinary linear regression is no longer appropriate. The hotel manager collected survey data measuring:</p>
<ul>
<li>Anticipated guilt if not joining the programme</li>
<li>Perceived attractiveness of the service robot</li>
<li>Age</li>
<li>Gender</li>
</ul>
<p>The objective is to predict whether a consumer joins the programme. The relationship can be expressed as:</p>
<p>JoinGLP ~ Guilt + Attract + Age + Gender + error</p>
<p>Unlike linear regression, logistic regression predicts the probability that a customer belongs to one of two groups. For example:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Probability</th>
<th>Predicted Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.90</td>
<td>Join GLP</td>
</tr>
<tr class="even">
<td>0.75</td>
<td>Join GLP</td>
</tr>
<tr class="odd">
<td>0.60</td>
<td>Join GLP</td>
</tr>
<tr class="even">
<td>0.40</td>
<td>Do Not Join</td>
</tr>
<tr class="odd">
<td>0.15</td>
<td>Do Not Join</td>
</tr>
</tbody>
</table>
<p>A probability greater than 0.50 is typically classified as a “Join”.</p>
</section>
<section id="the-logistic-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="the-logistic-regression-model">The Logistic Regression Model</h2>
<p>Linear regression predicts a score:</p>
<p><span class="math display">\[\begin{equation}

Y=\beta_0 + \beta_1X_1 + \beta_2X_2 + \beta_3X_3 ...

\end{equation}\]</span></p>
<p>Logistic regression predicts the log-odds of an event occurring:</p>
<p><span class="math display">\[\begin{equation} \ln\left(\frac{p}{1-p}\right)=\beta_0+\beta_1X_1+\beta_2X_2+\beta_3X_3+\beta_4X_4

\end{equation}\]</span></p>
<p>where:</p>
<ul>
<li>p = probability of joining the GLP</li>
<li><span class="math inline">\(X_1\)</span> = Guilt</li>
<li><span class="math inline">\(X_2\)</span> = Attractiveness</li>
<li><span class="math inline">\(X_3\)</span> = Age</li>
<li><span class="math inline">\(X_4\)</span> = Gender</li>
</ul>
<p>Fortunately, SPSS performs all calculations automatically. Our main objective is interpretation.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The coefficients from logistic regression are not interpreted in the same way as ordinary regression coefficients. Instead, we typically interpret the <span class="math inline">\(Exp(\beta)\)</span> values, which are known as <strong>odds ratios</strong>. <span class="math inline">\(Exp(\beta)\)</span> reads as exponential <span class="math inline">\(\beta\)</span>, i.e., <span class="math inline">\(Exp(\beta) = e^{\beta}\)</span>, where <em>e</em> is the base of the natural logarithm, approximately equal to 2.718.</p>
</div>
</div>
</section>
<section id="conducting-logistic-regression-in-spss" class="level2">
<h2 class="anchored" data-anchor-id="conducting-logistic-regression-in-spss">Conducting Logistic Regression in SPSS</h2>
<p>Open HotelGLP_Logistic.sav</p>
<p>Click:</p>
<p>Analyze → Regression → Binary Logistic</p>
<p>Move:</p>
<ul>
<li><p>JoinGLP into the Dependent box</p></li>
<li><p>Guilt, Attract, Age, Gender into Covariates</p></li>
</ul>
<p>Click <strong>OK</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/logistic_dialogue.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<p>SPSS produces several output tables.</p>
<p>The most important are:</p>
<ol type="1">
<li><p>Omnibus Tests of Model Coefficients</p></li>
<li><p>Model Summary</p></li>
<li><p>Classification Table</p></li>
<li><p>Variables in the Equation</p></li>
</ol>
</section>
<section id="omnibus-tests-of-model-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="omnibus-tests-of-model-coefficients">Omnibus Tests of Model Coefficients</h2>
<section id="is-the-model-useful" class="level3">
<h3 class="anchored" data-anchor-id="is-the-model-useful">Is the model useful?</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/logistic_omnibus.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<p>The Omnibus Tests of Model Coefficients table evaluates whether the set of predictors collectively improves prediction of the dependent variable compared with a model containing no predictors.</p>
<p>The null hypothesis is:</p>
<p><span class="math display">\[\begin{equation}
H_0:\beta_{Guilt}=\beta_{Attract}=\beta_{Age}=\beta_{Gender}=0
\end{equation}\]</span></p>
<p>In other words, none of the predictors help explain consumers’ decision to join the green loyalty programme.</p>
<p>The alternative hypothesis is:</p>
<p><span class="math display">\[\begin{equation}
H_1:\text{At least one predictor has a non-zero effect.}
\end{equation}\]</span></p>
<p>The p-value is less than .001. Therefore, we reject the null hypothesis and conclude that the model is statistically significant.</p>
<p>This means that the set of predictors (<code>Guilt</code>, <code>Attract</code>, <code>Age</code>, and <code>Gender</code>) collectively improves our ability to predict whether consumers join the green loyalty programme.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The logistic regression model is meaningful, <span class="math inline">\(\chi^2(4) = 473.548, \, p &lt; .001\)</span>.</p>
<p>Therefore, we can proceed to examine the remaining output tables to determine which variables significantly influence consumers’ decision to join the green loyalty programme.</p>
</div>
</div>
</section>
<section id="reporting-the-result" class="level3">
<h3 class="anchored" data-anchor-id="reporting-the-result">Reporting the Result</h3>
<p>A typical write-up would be:</p>
<blockquote class="blockquote">
<p>The Omnibus Test of Model Coefficients was significant, <span class="math inline">\(\chi^2(4) = 473.548, \, p &lt; .001\)</span>, indicating that the set of predictors significantly improved prediction of consumers’ decision to join the green loyalty programme compared with a model containing no predictors.</p>
</blockquote>
</section>
</section>
<section id="model-summary" class="level2">
<h2 class="anchored" data-anchor-id="model-summary">Model Summary</h2>
<p>How well does the model fit?</p>
<p><img src="images/logistic_summary.png" class="img-fluid quarto-figure quarto-figure-center" style="width:70.0%"> The Model Summary table provides information about how well the logistic regression model fits the data.</p>
<p>The most commonly reported statistic is the <span class="math inline">\(\text{Nagelkerke } R^2\)</span>.</p>
<p>In this example, <span class="math inline">\(\text{Nagelkerke } R^2 = 0.218\)</span>.</p>
<p>This indicates that the predictors (<code>Guilt</code>, <code>Attract</code>, <code>Age</code>, and <code>Gender</code>) explain approximately <strong>21.8%</strong> of the variation in consumers’ decisions to join the green loyalty programme.</p>
<p>This value suggests that the model has a moderate ability to explain consumers’ joining behaviour. In other words, the predictors help explain why some consumers join the programme and others do not, although additional factors not included in the model also influence joining decisions.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Unlike multiple regression, logistic regression does not produce a traditional <span class="math inline">\(R^2\)</span>. Instead, SPSS reports several <span class="math inline">\(\text{Pseudo-} R^2\)</span> measures, including Cox &amp; Snell <span class="math inline">\(R^2\)</span> and Nagelkerke <span class="math inline">\(R^2\)</span>.</p>
<p>Among the two measures, <span class="math inline">\(\text{Nagelkerke } R^2\)</span> is generally preferred because its maximum value is 1, making it easier to interpret.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\text{Pseudo-} R^2\)</span> values are generally lower than the <span class="math inline">\(R^2\)</span> values obtained from multiple regression.</p>
<p>Therefore, a Nagelkerke <span class="math inline">\(R^2\)</span> of 0.218 should not be interpreted as a weak model. In consumer and marketing research, values in this range are often considered meaningful.</p>
</div>
</div>
<section id="reporting-the-result-1" class="level3">
<h3 class="anchored" data-anchor-id="reporting-the-result-1">Reporting the Result</h3>
<p>A typical write-up would be:</p>
<blockquote class="blockquote">
<p>The logistic regression model explained approximately 21.8% of the variation in consumers’ decision to join the green loyalty programme, as indicated by the Nagelkerke <span class="math inline">\(\text{Nagelkerke } R^2\)</span> value of 0.218.</p>
</blockquote>
</section>
</section>
</section>
<section id="classification-table" class="level1">
<h1>Classification Table</h1>
<p>How accurate is the model?</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/logistic_classification_base.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<p>The Classification Table shows how accurately the model classifies consumers into the two categories of the dependent variable:</p>
<ul>
<li><code>JoinGLP = 0</code> (Did Not Join)</li>
<li><code>JoinGLP = 1</code> (Joined)</li>
</ul>
<p>The output shown above is for <strong>Step 0</strong>, which is the <strong>baseline model</strong> containing only the constant and no predictors.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Observed</th>
<th style="text-align: right;">Predicted 0</th>
<th style="text-align: right;">Predicted 1</th>
<th style="text-align: right;">% Correct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>JoinGLP = 0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">465</td>
<td style="text-align: right;">0.0%</td>
</tr>
<tr class="even">
<td>JoinGLP = 1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3541</td>
<td style="text-align: right;">100.0%</td>
</tr>
<tr class="odd">
<td><strong>Overall Percentage</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>88.4%</strong></td>
</tr>
</tbody>
</table>
<p>Notice that the model predicts <strong>every respondent</strong> as belonging to category 1 (Join GLP). Consequently:</p>
<ul>
<li>None of the non-joiners are classified correctly.</li>
<li>All joiners are classified correctly.</li>
<li>Overall accuracy is 88.4%.</li>
</ul>
<p>This may appear to be an excellent result. However, it is actually not very impressive because the model has not yet used any predictors.</p>
<p>The reason is that most respondents in the sample joined the programme:</p>
<p><span class="math display">\[
\frac{3541}{3541+465}=0.884
\]</span></p>
<p>or <strong>88.4%</strong>.</p>
<p>Therefore, a model that simply predicts that everyone joins the programme would already achieve an accuracy rate of 88.4%.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Do not interpret the Step 0 classification accuracy as evidence of a good model.</p>
<p>The Step 0 model contains no predictors and merely classifies every respondent into the largest group.</p>
</div>
</div>
<section id="why-is-this-table-useful" class="level3">
<h3 class="anchored" data-anchor-id="why-is-this-table-useful">Why Is This Table Useful?</h3>
<p>The Step 0 classification table provides a <strong>baseline accuracy rate</strong> against which the final logistic regression model can be compared.</p>
<p>In this study:</p>
<ul>
<li>Baseline accuracy = <strong>88.4%</strong></li>
<li>Final model accuracy = <strong>88.7%</strong> (we will discuss now)</li>
</ul>
<p>This comparison allows us to evaluate whether the predictors meaningfully improve prediction beyond simply classifying everyone into the largest group.</p>
<p>Now, let us look at the final classification table where you will see the final model accuracy of <strong>88.7%</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/logistic_classification.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<p>The final classification table indicates that:</p>
<ul>
<li><p>Of the 465 consumers who did <strong>not</strong> join the programme, only 44 were correctly classified.</p></li>
<li><p>Of the 3,541 consumers who <strong>joined</strong> the programme, 3,509 were correctly classified.</p></li>
<li><p>The model correctly classified <strong>88.7%</strong> of all consumers.</p></li>
</ul>
<p>At first glance, an accuracy rate of 88.7% appears impressive. However, we must compare this result with the <strong>baseline model</strong> (Step 0).</p>
<p>Recall that the Step 0 model achieved an accuracy rate of <strong>88.4%</strong> simply by classifying everyone as a joiner.</p>
<p>The logistic regression model improves the classification accuracy only slightly:</p>
<p><span class="math display">\[
88.7\% - 88.4\% = 0.3\%
\]</span></p>
<p>Thus, although the model is statistically significant, its overall classification accuracy is only marginally better than the baseline model.</p>
</section>
<section id="sensitivity-and-specificity" class="level3">
<h3 class="anchored" data-anchor-id="sensitivity-and-specificity">Sensitivity and Specificity</h3>
<p>The classification table also provides insight into which group is predicted well.</p>
<p>The model correctly identifies:</p>
<ul>
<li><p><strong>99.1%</strong> of consumers who joined the programme (high sensitivity).</p></li>
<li><p>Only <strong>9.5%</strong> of consumers who did not join the programme (low specificity).</p></li>
</ul>
<p>This indicates that the model is very good at identifying consumers who join the programme but performs poorly at identifying consumers who do not join.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The logistic regression model correctly classified 88.7% of consumers.</p>
<p>However, this represents only a small improvement over the baseline accuracy of 88.4%. The model is highly accurate in identifying consumers who joined the programme (99.1%) but performs poorly in identifying consumers who did not join (9.5%).</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>When one outcome category is much larger than the other, overall classification accuracy can be misleading.</p>
<p>In this dataset, 88.4% of respondents joined the programme. Therefore, a model can achieve high accuracy simply by predicting that everyone joins.</p>
<p>Always examine the percentage correctly classified for each category, not just the overall percentage.</p>
</div>
</div>
</section>
<section id="reporting-the-result-2" class="level3">
<h3 class="anchored" data-anchor-id="reporting-the-result-2">Reporting the Result</h3>
<p>A typical write-up would be:</p>
<blockquote class="blockquote">
<p>The logistic regression model correctly classified 88.7% of respondents. The model correctly identified 99.1% of consumers who joined the green loyalty programme but only 9.5% of consumers who did not join. Compared with the baseline classification accuracy of 88.4%, the model provided only a modest improvement in predictive accuracy.</p>
</blockquote>
<p>@@@@@@@@@@</p>
<p>ObservedPredicted CorrectlyNot Join72%Join80%Overall Accuracy76% This means the model correctly classifies 76% of customers. The classification table provides an intuitive measure of predictive performance.</p>
<p>Variables in the Equation Which variables matter? images/logistic_coeffs.png Example output:</p>
<p>VariableBSig.Exp(B)Guilt.55.0011.73Attract.80.0002.23Age-.03.0200.97Gender.12.4201.13 We interpret significance first. Step 1: Statistical Significance Variables are significant when: Plain Text1p &lt; .05Show more lines Therefore: ✅ Guilt significant ✅ Attract significant ✅ Age significant ❌ Gender not significant</p>
<p>Step 2: Interpret Odds Ratios The Exp(B) column reports the odds ratio. Example 1: Guilt Plain Text1Exp(B) = 1.73Show more lines For every one-unit increase in Guilt, the odds of joining the GLP increase by 73%.</p>
<p>Example 2: Attractiveness Plain Text1Exp(B) = 2.23Show more lines For every one-unit increase in Attractiveness, the odds of joining the GLP increase by 123%. Attractiveness appears to have a strong effect.</p>
<p>Example 3: Age Plain Text1Exp(B) = 0.97Show more lines Values below 1 indicate a negative effect. Each additional year of age decreases the odds of joining by approximately 3%.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>A quick rule: Exp(B) &gt; 1 → Positive effect Exp(B) &lt; 1 → Negative effect Exp(B) = 1 → No effect</p>
</div>
</div>
<p>One-Sided Versus Two-Sided Tests As with ordinary regression: SPSS reports p-values for two-sided tests. If your hypothesis is directional (e.g., Guilt positively influences joining intention), divide the reported p-value by two. Example: Plain Text1SPSS p-value = .020Show more lines One-sided p-value: Plain Text1.020 / 2 = .010Show more lines Since .010 &lt; .05, the relationship is significant in the hypothesised direction.</p>
<p>Predicting Probabilities Suppose the estimated model is: ln⁡(p1−p)=−2.5+0.55(Guilt)+0.80(Attract)−0.03(Age)+0.12(Gender)() = -2.5 + 0.55(Guilt) + 0.80(Attract) - 0.03(Age) + 0.12(Gender)ln(1−pp​)=−2.5+0.55(Guilt)+0.80(Attract)−0.03(Age)+0.12(Gender) For a customer with:</p>
<p>Guilt = 5 Attract = 6 Age = 25 Gender = 0</p>
<p>the log-odds become: 1.851.851.85 The predicted probability is: p=e1.851+e1.85p= {1+e^{1.85}}p=1+e1.85e1.85​ p=0.864p=0.864p=0.864 Therefore: The customer has an 86.4% predicted probability of joining the GLP.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Task Using the regression equation reported in SPSS, calculate the probability that a 20-year-old female customer with:</p>
<p>Guilt = 4 Attract = 5</p>
<p>will join the GLP.</p>
</div>
</div>
<p>Assessing Multicollinearity Multicollinearity can also affect logistic regression. The same diagnostic procedures apply.</p>
<p>Examine correlations among predictors. Inspect VIF values using a linear regression with the same set of predictors.</p>
<p>Guidelines: Plain Text1Correlation &gt; .70Show more lines Use caution. Plain Text1VIF &gt; 10Show more lines Potential multicollinearity problem. Plain Text1VIF &gt; 5Show more lines Worth investigating.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Task Run a linear regression using Guilt, Attract, Age, and Gender as predictors. Inspect the VIF values. Does the model suffer from multicollinearity?</p>
</div>
</div>
</section>
<section id="reporting-logistic-regression-results" class="level2">
<h2 class="anchored" data-anchor-id="reporting-logistic-regression-results">Reporting Logistic Regression Results</h2>
<p>A typical write-up might be:</p>
<p>A binary logistic regression was conducted to examine factors influencing consumers’ decision to join a green loyalty programme. The model was significant, χ²(4) = 42.61, p &lt; .001, indicating that the predictors collectively improved prediction. The model explained approximately 29% of variation in joining behaviour (Nagelkerke R² = .29) and correctly classified 76% of respondents. Perceived attractiveness (OR = 2.23, p &lt; .001), anticipated guilt (OR = 1.73, p = .001), and age (OR = 0.97, p = .020) significantly influenced joining behaviour. Gender was not significant (p = .420).</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>